### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by randoom15** [pytransitions/transitions-gui#10] opened 2020-06-05 18:10 UTC
Tried the sample code on my win10 pc, with tornado installed with pip

```
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by aleneum** [comment] 2020-06-08 15:49
Hi @randoom15,

this is probably related to this issue: https://github.com/tornadoweb/tornado/issues/2751

**Comment by randoom15** [comment] 2020-06-08 18:07
That might be it, will test later :)

**Comment by aleneum** [comment] 2020-06-25 08:40
I am closing this since there hasnt been new comments in quite a while. If this issue still persists and is caused by `transitions-gui`. feel free to comment anyway. I will open the issue again if needed.

**Closed by aleneum** 2020-06-25 08:40 UTC
